MULT = 1.0

FPS = 60

SCREEN_WIDTH = 900
SCREEN_HEIGHT = 700

LEVEL_NUM = 0
CURR_LEVEL = LEVEL_NUM

GO_HORIZONTAL = 0
GO_VERTICAL = 0

MOVE_SPEED = 5
CIRCLE_R_SIZE = 25

CIRCLE_POS_X = SCREEN_WIDTH // 2
CIRCLE_POS_Y = SCREEN_HEIGHT // 2

GOOD_DOT_NUM = 0
GOOD_DOT_R_SIZE = 10

BAD_DOT_NUM = 0
BAD_DOT_R_SIZE = 15

PURPLE_DOT_R_SIZE = 10
BIG_ACTION_DOT_ON = 0

CHANGE_EVERY = int(25 * (1 / MULT))
CHANGE_COUNTER = 0

TICK = 1
CURR_TICK = TICK
BIG_ACTION = 0

WHITE_STATUS = 0
WHITE_EVERY = CHANGE_EVERY * 60
WHITE_AXIS = 1
WHITE_POS = SCREEN_WIDTH // 2

SHIELD = 0

running = True
running_game = True
running_summ = True

DOTS = []


def set_starting_conditions() -> None:
    global LEVEL_NUM, GO_HORIZONTAL, GO_VERTICAL, CIRCLE_POS_X, CIRCLE_POS_Y, GOOD_DOT_NUM, BAD_DOT_NUM, \
        BIG_ACTION_DOT_ON, CHANGE_COUNTER, TICK, CURR_LEVEL, CURR_TICK, CIRCLE_R_SIZE, DOTS, BIG_ACTION, SHIELD
    LEVEL_NUM = 0
    CURR_LEVEL = LEVEL_NUM

    GO_HORIZONTAL = 0
    GO_VERTICAL = 0

    CIRCLE_POS_X = SCREEN_WIDTH // 2
    CIRCLE_POS_Y = SCREEN_HEIGHT // 2
    CIRCLE_R_SIZE = 25
    DOTS = []

    GOOD_DOT_NUM = 0
    BAD_DOT_NUM = 0
    BIG_ACTION_DOT_ON = 0

    CHANGE_COUNTER = 0
    BIG_ACTION = 0

    SHIELD = 0

    TICK = 1
    CURR_TICK = TICK